// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFIhlfmLI5wn-tQik3O8eerPDzhCPypx4',
    appId: '1:330383229148:android:c147743a94600d7762f419',
    messagingSenderId: '330383229148',
    projectId: 'sign-speak-app-aff74',
    storageBucket: 'sign-speak-app-aff74.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDta5GPl3oiGogvr1mr_b9UlJZQ83hKLmQ',
    appId: '1:330383229148:ios:06078c6f39ee03d162f419',
    messagingSenderId: '330383229148',
    projectId: 'sign-speak-app-aff74',
    storageBucket: 'sign-speak-app-aff74.firebasestorage.app',
    androidClientId: '330383229148-b3rl8t7ub57oat2qpsbif2sj7rn6mh4o.apps.googleusercontent.com',
    iosClientId: '330383229148-6s30o2a2kmsp47o63gmv684caidt1j8p.apps.googleusercontent.com',
    iosBundleId: 'com.comp499.senior-project.sign-speak',
  );
}
